experiment:
  - dataset: ["Beef", "GunPoint", "Yoga"]
    classifier: ["mini-rocket", "catch22"]
    random_seed: [0,1,2]

    strategy:
      - type: "baseline"
        mode: "none"
        params: {}

      - type: "temporal_downsampling"
        mode: "uniform"
        params:
          p: [0.1, 0.3, 0.5, 0.7, 0.9]

      - type: "difficulty_selection"
        mode: "distance"
        params:
          p: [0.1, 0.3, 0.5, 0.7, 0.9]

      - type: "label_quality"
        mode: "flip"
        params:
          p: [0.1, 0.3, 0.5, 0.7, 0.9, 1.0]
        
      - type: "feature_quality"
        mode: "gaussian"
        params:
          p: [0.1, 0.3, 0.5, 0.7, 0.9, 1.0]

