experiment:
  - dataset: ["Beef", "GunPoint", "Yoga"]
    classifier: ["mini-rocket", "catch22"]
    random_seed: [0,1,2]

    strategy:
      - type: "baseline"
        mode: "none"
        params: {}

      - type: "length_reduction"
        mode: "random"
        params:
          reduction_fraction: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

      - type: "number_instances"
        mode: "random"
        params:
          reduction_ratio: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

      - type: "label_flipping"
        mode: "random"
        params:
          flip_ratio: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
        
      - type: "feature_quality"
        mode: "normal"
        params:
          noise_level: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

